# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QFileDialog

def resource_path(relative_path):
    try:
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")
    return os.path.join(base_path, relative_path)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(16, 22, 33);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.left_screen_2 = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_screen_2.sizePolicy().hasHeightForWidth())
        self.left_screen_2.setSizePolicy(sizePolicy)
        self.left_screen_2.setStyleSheet("#left_screen_2{\n"
"border-width: 2px;\n"
"border-bottom-style: solid;\n"
"border-color: rgb(66,79,105);\n"
"}")
        self.left_screen_2.setObjectName("left_screen_2")
        self.left_screen = QtWidgets.QVBoxLayout(self.left_screen_2)
        self.left_screen.setContentsMargins(9, -1, -1, -1)
        self.left_screen.setObjectName("left_screen")
        self.bar = QtWidgets.QWidget(parent=self.left_screen_2)
        self.bar.setStyleSheet(".QPushButton{\n"
"    border:none;\n"
"}\n"
"#bar{\n"
"     border-width: 2px;\n"
"    border-style: solid;\n"
"    border-left-style: solid;\n"
"    border-color: rgb(66,79,105);\n"
"    border-radius: 5px;\n"
"}")
        self.bar.setObjectName("bar")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.bar)
        self.horizontalLayout_14.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        # В секции horizontalLayout_6 добавьте эту кнопку:




        # self.pushButton_2 = QtWidgets.QPushButton(parent=self.bar)
        # self.pushButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        # self.pushButton_2.setText("")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("ui/src/icons/image.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        # self.pushButton_2.setIcon(icon)
        # self.pushButton_2.setIconSize(QtCore.QSize(27, 27))
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.horizontalLayout_6.addWidget(self.pushButton_2)

        self.pushButton = QtWidgets.QPushButton(parent=self.bar)
        self.pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/video.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(27, 27))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.bar)
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_6.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/ipcamera.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget = QtWidgets.QWidget(parent=self.bar)
        self.widget.setObjectName("widget")
        self.horizontalLayout_11.addWidget(self.widget)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 53))
        self.pushButton_5.setStyleSheet("background-color: rgb(16, 35, 74);")
        self.pushButton_5.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/play.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon3)
        self.pushButton_5.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.bar)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/pause.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_2 = QtWidgets.QWidget(parent=self.bar)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_13.addWidget(self.widget_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.bar)
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_3.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/stop.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_13.addWidget(self.pushButton_3)

        # В секции horizontalLayout_6 добавьте эту кнопку:
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.bar)
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_7.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(resource_path("ui/src/icons/record_off.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon7)
        self.pushButton_7.setIconSize(QtCore.QSize(27, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_13.addWidget(self.pushButton_7)

        self.horizontalLayout_14.addLayout(self.horizontalLayout_13)
        self.left_screen.addWidget(self.bar)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label = QtWidgets.QLabel(parent=self.left_screen_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(resource_path("ui/src/images/image.png")))
        self.label.setObjectName("label")
        self.horizontalLayout_10.addWidget(self.label)
        self.left_screen.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_15.addWidget(self.left_screen_2)
        self.right_screen = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_screen.sizePolicy().hasHeightForWidth())
        self.right_screen.setSizePolicy(sizePolicy)
        self.right_screen.setMaximumSize(QtCore.QSize(300, 16777215))
        self.right_screen.setStyleSheet("#right_screen{\n"
"     border-width: 2px;\n"
"    border-bottom-style: solid;\n"
"    border-left-style: solid;\n"
"    border-color: rgb(66,79,105);\n"
"}")
        self.right_screen.setObjectName("right_screen")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_screen)
        self.verticalLayout_2.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.right_screen)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font: 700 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:10px;")
        self.label_2.setMidLineWidth(5)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setStyleSheet("#frame_4{\n"
"     border-width: 2px;\n"
"    border-style: solid;\n"
"    border-color: rgb(66,79,105);\n"
"border-radius:5px;\n"
"}")
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_6.setStyleSheet("font: 700 9pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
#         self.progressBar = QtWidgets.QProgressBar(parent=self.frame_5)
#         self.progressBar.setStyleSheet("    border: none;\n"
# "    border-radius: 20px;\n"
# "    background-color: #222;\n"
# "color: transparent;\n"
# "    height: 10px;")
#         self.progressBar.setProperty("value", 24)
#         self.progressBar.setObjectName("progressBar")
#         self.verticalLayout_9.addWidget(self.progressBar)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.right_screen)
        self.frame_2.setStyleSheet("")
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_3.setStyleSheet("font: 700 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:10px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(66,79,105);\n"
"border-radius:5px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_7.setStyleSheet("font: 700 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_5.setStyleSheet("font: 700 18pt \"Roboto\";\n"
"color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.right_screen)
        self.widget_3.setStyleSheet("border:2px solid #fffffff;")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_4.setStyleSheet("font: 700 12pt \"Roboto\";\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:10px;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.frame_7 = QtWidgets.QFrame(parent=self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(66,79,105);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_8.setStyleSheet("\n"
"font: 700 12pt \"Roboto\";\n"
"color: rgb(186,188,191);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.label_14 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)

        self.horizontalLayout_2.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_9.setStyleSheet("\n"
"font: 700 12pt \"Roboto\";\n"
"color: rgb(186,188,191);\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.horizontalLayout_2.addWidget(self.frame_9)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_15.addWidget(self.right_screen)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Detection Results"))
        self.label_6.setText(_translate("MainWindow", "Speed Limit 50"))
        self.label_3.setText(_translate("MainWindow", "Performance"))
        self.label_7.setText(_translate("MainWindow", "Frames Per Second (FPS)"))
        self.label_5.setText(_translate("MainWindow", "0.0"))
        self.label_4.setText(_translate("MainWindow", "Model Information"))
        self.label_8.setText(_translate("MainWindow", "Model"))
        self.label_9.setText(_translate("MainWindow", "Weights"))
        self.label_10.setText(_translate("MainWindow", "Device"))
        self.label_14.setText(_translate("MainWindow", "Resours info"))
        self.label_11.setText(_translate("MainWindow", ""))
        self.label_12.setText(_translate("MainWindow", ""))
        self.label_13.setText(_translate("MainWindow", ""))
        self.label_15.setText(_translate("MainWindow", ""))


